### ISSUE TITLE
Can't work

### ISSUE THREAD

**Issue by nyngwang** [Sanix-Darker/snips.nvim#1]
It only prints this: after selection and calling `:SnipsCreate`:

```
cat /tmp/lua_ASV6wF.lua | ssh snips.sh
```

**Comment by Sanix-Darker** [comment]
when running `echo "test" | ssh snips.sh` on your terminal, what do you have ?

**Comment by nyngwang** [comment]
Well but where is the `snips.sh` at the first place?

Oh, ok I got this:

```
Pseudo-terminal will not be allocated because stdin is not a terminal.
The authenticity of host 'snips.sh (143.244.212.58)' can't be established.
ED25519 key fingerprint is SHA256:5gsYe11pDptwLuVC65Sd40nDAVcP4Vs1qFfzj2Rm37A.
```

**Comment by nyngwang** [comment]
Now it works :) https://snips.sh/f/kdA3Baapaw, I guess you will need to hint people to confirm the connection in your README.md.

**Comment by Sanix-Darker** [comment]
Thanks for reporting this, i updated the README for that !
https://github.com/Sanix-Darker/snips.nvim/commit/cb82a271f9b0056106ede6441432f893990b876a
