### ISSUE TITLE
Use `--ext` parameter to force known file extension

### ISSUE THREAD

**Issue by robherley** [Sanix-Darker/snips.nvim#10]
👋 This is an awesome project, thanks for building this integration!

I noticed this comment:

https://github.com/Sanix-Darker/snips.nvim/blob/967e7db0275298721e15a0f17fcb6fe0a85d19fe/lua/snips.lua#L24-L27

You can actually specify the extension as a parameter

```
cat <file> | ssh snips.sh -- --ext <extension>
```

e.g.

```
$ cat main.go | ssh snips.sh -- -ext rs     
┃ File Uploaded 📤                              
┃ id: fkSiwnB6Ue                                
┃ size: 1.7 kB • type: rust • visibility: public
                           
┃ SSH 📠                   
┃ ssh f:fkSiwnB6Ue@snips.sh
┃ URL 🔗                       
┃ https://snips.sh/f/fkSiwnB6Ue
```

Even though the file has golang content, it will be marked as rust because of the `rs` extension parameter.

**Comment by Sanix-Darker** [comment]
interesting, thanks @robherley , i will update the code in that way 👌🏽
