### ISSUE TITLE
Is it possible to make `:SnipsCreate` async?

### ISSUE THREAD

**Issue by nyngwang** [Sanix-Darker/snips.nvim#15]
I experienced frozen Neovim after calling `:SnipsCreate` on the visual-select lines. It will be great if we could run it in the background. (notice: being async has its own trouble, e.g. the user might move his cursor around after calling it and the split might be created anywhere)

**Comment by Sanix-Darker** [comment]
well, that's a good point, i will have a look into it soon, thanks for creating an issue on that !

**Comment by Pagliacii** [comment]
I am working on it, comparing `vim.loop` with [nvim-lua/plenary.nvim](https://github.com/nvim-lua/plenary.nvim). Maybe I will submit a pr at tonight.
