### ISSUE TITLE
add an option for a custom self hosted snips.sh instance

### ISSUE THREAD

**Issue by Sanix-Darker** [Sanix-Darker/snips.nvim#18]
since snips.sh is open source, anyone can self hosted his instance and want to use this plugin to connect on it,
we need to have a new option for that in the `setup()`, something like : 
```lua
local opts = {
  snips_host = "snips.sanix-darker.com",
}
require("snips.nvim").setup(opts)
```

**Comment by nyngwang** [comment]
How do I deploy my own instance? Is this related to privacy issues? But then why share my code in the first place? Or maybe people want to do something like "internal sharing"(sharing code within a corporation or group)?

**Comment by Pagliacii** [comment]
Look at [this](https://github.com/robherley/snips.sh/blob/main/docs/self-hosting.md) 🚀
