### ISSUE TITLE
Error while setting up with lazy.nvim

### ISSUE THREAD

**Issue by System3-2** [Sanix-Darker/snips.nvim#2]
i tried to setup with `lazy.nvim` but when i paste this
 ```lua
--HACK: Snips load
require("snips.nvim").setup()
-- this will just make sure the plugin is available
-- maybe planing on adding more customisations ? idk...
```
i get this error
![Screenshot from 2023-06-16 22-22-36](https://github.com/Sanix-Darker/snips.nvim/assets/97600170/c318938a-bd4a-40dc-81e3-d433fafc8e99)

i also have this code in my `/plugins/snips.lua` file

```lua
return {
  {
    "Sanix-Darker/snips.nvim",
  },
}

```

**Comment by Pagliacii** [comment]
You can use this:

```lua
return {
  {
    "Sanix-Darker/snips.nvim",
    config = true,
    cmd = { "SnipsCreate" },  -- optional, make the plugin loads at cmd executed
  },
}
```

Or

```lua
require("snips").setup()
```

**Comment by Sanix-Darker** [comment]
Thanks @Pagliacii , i didn't test it myself since I don't have/use lazy.nvim !
I made this PR : https://github.com/Sanix-Darker/snips.nvim/pull/5
If everything works for you, I will merge the PR @OlojaMuyiwa .

**Comment by System3-2** [comment]
> You can use this:
> 
> ```lua
> return {
>   {
>     "Sanix-Darker/snips.nvim",
>     config = true,
>     cmd = { "SnipsCreate" },  -- optional, make the plugin loads at cmd executed
>   },
> }
> ```
> 
> Or
> 
> ```lua
> require("snips").setup()
> ```

this works. thanks

**Comment by System3-2** [comment]
> Thanks @Pagliacii , i didn't test it myself since I don't have/use lazy.nvim ! I made this PR : #5 If everything works for you, I will merge the PR @OlojaMuyiwa .

yeah it worked for me.
