### ISSUE TITLE
Feature Request: Provide a setup option to have a persistent file to store all generated links

### ISSUE THREAD

**Issue by nyngwang** [Sanix-Darker/snips.nvim#3]
As title. Sometimes I like to create many links and copy-paste them at once. It's also great if I can have a project-local file that stores those links I have generated.

What do you think?

**Comment by Sanix-Darker** [comment]
I think it's a really good idea, let say a file path, the user can specify as an option to the setup of the plugin, and can be stored as a simple log format ?
```lua
require("snips.nvim").setup({
  snips_links_path='~/.snips.pah'
})
```

with something like this inside the file ? : 
```
https://snips.sh/f/yMOp0IlTvs  • size: 90 B • type: lua
https://snips.sh/f/R9FUxLteFI  • size: 42 B • type: plaintext
.....
```

**Comment by Pagliacii** [comment]
Maybe using JSON format will be more structural.

**Comment by Sanix-Darker** [comment]
ok so, the thing is, snips.sh does already have a nice UI to search and list all uploaded snips !
You only need to `ssh snips.sh` !
I propose you guys an alternative !
A simple SnipsList to get that UI in a new tab (:term and ssh-client snips.sh)


![Peek 2023-06-20 10-22](https://github.com/Sanix-Darker/snips.nvim/assets/22576758/74f4cf63-d0ee-4077-ac74-51cc73b6017f)

You can even enter and check for the code etc...

What do you think ?

**Comment by nyngwang** [comment]
> You only need to `ssh snips.sh`!

Then I can just use that with my terminal buffer plugin: (So I'm OK with the current status, thanks for the info!)

<img src="https://github.com/Sanix-Darker/snips.nvim/assets/24765272/cbb8ba8f-6686-45ca-b343-8fabdf1b3c9e" width="600">

**Comment by Sanix-Darker** [comment]
I added a support for it to the plugin at the same time : https://github.com/Sanix-Darker/snips.nvim/pull/9
`SnipsList` !
That command doesn't require an "extra other plugin".

Let me know if I can close this issue then @nyngwang

**Comment by nyngwang** [comment]
Let me close this for you :) Thanks for the active helping!
