### ISSUE TITLE
Automatically yank the link of the url

### ISSUE THREAD

**Issue by Sanix-Darker** [Sanix-Darker/snips.nvim#4]
Yank automatically the link of the generated snips to the clipboard.
Could be great to have this as an option from the setup.

**Comment by Pagliacii** [comment]
I think you can print the link instead of the executing message.

https://github.com/Sanix-Darker/snips.nvim/blob/ae2afe254581be47f83d1210a3fb6a3a244b5ad5/lua/snips.lua#L84
