### ISSUE TITLE
Windows built-in ssh client doesn't work

### ISSUE THREAD

**Issue by Pagliacii** [Sanix-Darker/snips.nvim#6]
FYI: If using the Windows built-in ssh client, the `SnipsCreate` doesn't work. When I change to use cygwin ssh client, it works correctly.

How to remove built-in ssh client:

> Open Settings, then go to Apps > Apps & Features. Go to Optional Features. In the list, select OpenSSH Client or OpenSSH Server. Select Uninstall.

**Comment by Sanix-Darker** [comment]
legit !
am just wondering, Is it not better to add a new option for selecting the "ssh client" ? 🤔

**Comment by Pagliacii** [comment]
Yep, I will open a new pull request at tonight.
